export const BASE_URI = 'oops.now.sh';
export const GITHUB_URI = 'github.com';
export const GITHUB_USER = 'jecassis';
export const GITHUB_REPO = 'blog';
export const SRC_URL = `https://${GITHUB_URI}/${GITHUB_USER}/${GITHUB_REPO}`;
export const BLOG_TITLE = 'Kernel Oops';
export const BLOG_SUBTITLE = 'Blog';
export const AUTHOR_NAME = 'Kernel Oops';
export const AUTHOR_EMAIL = 'KernelOops [at] outlook [dot] com';
